### ISSUE TITLE
Create Validation Instance on Toolforge

### ISSUE THREAD

**Issue by victorgois** [WikiMovimentoBrasil/capx-frontend#57]
**Describe the feature or bug**
It aims to create a validation branch to test and watch bugs.

**If it is a bug, describe the steps to reproduce the behavior:**

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem or visually describe your feature.

**Additional context**

**Comment by albertoleoncio** [comment]
```bash
albertoleoncio@tools-bastion-13:~$ become capx-test
tools.capx-test@tools-bastion-13:~$ cd www/js
tools.capx-test@tools-bastion-13:~/www/js$ git clone https://github.com/WikiMovimentoBrasil/capx-frontend.git .
Cloning into '.'...
remote: Enumerating objects: 5995, done.
remote: Counting objects: 100% (258/258), done.
remote: Compressing objects: 100% (110/110), done.
remote: Total 5995 (delta 161), reused 207 (delta 143), pack-reused 5737 (from 1)
Receiving objects: 100% (5995/5995), 3.34 MiB | 11.58 MiB/s, done.
Resolving deltas: 100% (3203/3203), done.
Updating files: 100% (180/180), done.
tools.capx-test@tools-bastion-13:~/www/js$ webservice --mem 2G --cpu 2 node18 shell
tools.capx-test@shell-1734091111:~$ cd ~/www/js
tools.capx-test@shell-1734091111:~/www/js$ yarn install
yarn install v1.22.19
[1/4] Resolving packages...
warning @storybook/nextjs > @storybook/builder-webpack5 > webpack-dev-middleware > memfs@3.6.0: this will be v4
warning @storybook/nextjs > @storybook/builder-webpack5 > fork-ts-checker-webpack-plugin > memfs@3.6.0: this will be v4
[2/4] Fetching packages...
warning Pattern ["string-width@^4.1.0"] is trying to unpack in the same destination "/data/project/capx-test/.cache/yarn/v6/npm-string-width-cjs-4.2.3-269c7117d27b05ad2e536830a8ec895ef9c6d010-integrity/node_modules/string-width-cjs" as pattern ["string-width-cjs@npm:string-width@^4.2.0"]. This could result in non-deterministic behavior, skipping.
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
[3/4] Linking dependencies...
warning " > @primer/react@36.27.0" has incorrect peer dependency "styled-components@5.x".
warning "@primer/react > react-markdown@8.0.7" has unmet peer dependency "@types/react@>=16".
warning "@storybook/addon-essentials > @storybook/addon-docs > @mdx-js/react@3.1.0" has unmet peer dependency "@types/react@>=16".
warning "@storybook/nextjs > babel-loader@9.2.1" has unmet peer dependency "webpack@>=5".
warning "@storybook/nextjs > sass-loader@13.3.3" has unmet peer dependency "webpack@^5.0.0".
warning "@storybook/nextjs > style-loader@3.3.4" has unmet peer dependency "webpack@^5.0.0".
warning "@storybook/nextjs > node-polyfill-webpack-plugin@2.0.1" has unmet peer dependency "webpack@>=5".
warning "@storybook/nextjs > @pmmmwh/react-refresh-webpack-plugin@0.5.15" has unmet peer dependency "webpack@>=4.43.0 <6.0.0".
[4/4] Building fresh packages...
success Saved lockfile.
Done in 514.38s.
tools.capx-test@shell-1734091111:~/www/js$ yarn build
yarn run v1.22.19
$ next build
Attention: Next.js now collects completely anonymous telemetry regarding usage.
This information is used to shape Next.js' roadmap and prioritize features.
You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
https://nextjs.org/telemetry

   ▲ Next.js 14.1.3

   Creating an optimized production build ...
 ✓ Compiled successfully

./src/app/(auth)/profile/edit/components/EditProfileForm.tsx
73:5  Warning: React Hook useMemo has a missing dependency: 'handleLoadPictures'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps

./src/app/tag/components/TagProfileMainWrapper.tsx
61:6  Warning: React Hook useEffect has a missing dependency: 'props.language'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps

info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
 ✓ Linting and checking validity of types
 ✓ Collecting page data
   Generating static pages (5/19)  [=   ]
Error details: ex [Error]: Dynamic server usage: Page couldn't be rendered statically because it used `nextUrl.searchParams`. See more info here: https://nextjs.org/docs/messages/dynamic-server-error
    at Object.eP [as staticGenerationBailout] (/data/project/capx-test/www/js/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:29358)
    at n (/data/project/capx-test/www/js/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:33712)
    at Object.get (/data/project/capx-test/www/js/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:34359)
    at n (/data/project/capx-test/www/js/.next/server/app/api/capacity/route.js:1:946)
    at /data/project/capx-test/www/js/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:42490
    at /data/project/capx-test/www/js/node_modules/next/dist/server/lib/trace/tracer.js:133:36
    at NoopContextManager.with (/data/project/capx-test/www/js/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:7062)
    at ContextAPI.with (/data/project/capx-test/www/js/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:518)
    at NoopTracer.startActiveSpan (/data/project/capx-test/www/js/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:18093)
    at ProxyTracer.startActiveSpan (/data/project/capx-test/www/js/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:18854) {
  description: "Page couldn't be rendered statically because it used `nextUrl.searchParams`. See more info here: https://nextjs.org/docs/messages/dynamic-server-error",
  digest: 'DYNAMIC_SERVER_USAGE'
}
Tag API error: ex [Error]: Dynamic server usage: Page couldn't be rendered statically because it used `nextUrl.searchParams`. See more info here: https://nextjs.org/docs/messages/dynamic-server-error
    at Object.eP [as staticGenerationBailout] (/data/project/capx-test/www/js/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:29358)
    at n (/data/project/capx-test/www/js/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:33712)
    at Object.get (/data/project/capx-test/www/js/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:34359)
    at p (/data/project/capx-test/www/js/.next/server/app/api/tag/route.js:1:946)
    at /data/project/capx-test/www/js/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:42490
    at /data/project/capx-test/www/js/node_modules/next/dist/server/lib/trace/tracer.js:133:36
    at NoopContextManager.with (/data/project/capx-test/www/js/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:7062)
    at ContextAPI.with (/data/project/capx-test/www/js/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:518)
    at NoopTracer.startActiveSpan (/data/project/capx-test/www/js/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:18093)
    at ProxyTracer.startActiveSpan (/data/project/capx-test/www/js/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:18854) {
  description: "Page couldn't be rendered statically because it used `nextUrl.searchParams`. See more info here: https://nextjs.org/docs/messages/dynamic-server-error",
  digest: 'DYNAMIC_SERVER_USAGE'
   Generating static pages (9/19)  [==  ]
 ⚠ Unsupported metadata viewport is configured in metadata export in /oauth. Please move it to viewport export instead.
Read more: https://nextjs.org/docs/app/api-reference/functions/generate-viewport
 ⚠ Unsupported metadata viewport is configured in metadata export in /terms. Please move it to viewport export instead.
   Generating static pages (9/19)  [=== ]
 ⚠ Unsupported metadata viewport is configured in metadata export in /profile/edit. Please move it to viewport export instead.
Read more: https://nextjs.org/docs/app/api-reference/functions/generate-viewport
 ⚠ Unsupported metadata viewport is configured in metadata export in /profile/edit. Please move it to viewport export instead.
Read more: https://nextjs.org/docs/app/api-reference/functions/generate-viewport
 ⚠ Unsupported metadata viewport is configured in metadata export in /profile. Please move it to viewport export instead.
Read more: https://nextjs.org/docs/app/api-reference/functions/generate-viewport
 ⚠ Unsupported metadata viewport is configured in metadata export in /. Please move it to viewport export instead.
Read more: https://nextjs.org/docs/app/api-reference/functions/generate-viewport
 ⚠ Unsupported metadata viewport is configured in metadata export in /. Please move it to viewport export instead.
Read more: https://nextjs.org/docs/app/api-reference/functions/generate-viewport
 ⚠ Unsupported metadata viewport is configured in metadata export in /terms. Please move it to viewport export instead.
Read more: https://nextjs.org/docs/app/api-reference/functions/generate-viewport
 ⚠ Unsupported metadata viewport is configured in metadata export in /oauth. Please move it to viewport export instead.
   Generating static pages (9/19)  [ ===]
 ⚠ Unsupported metadata viewport is configured in metadata export in /_not-found. Please move it to viewport export instead.
Read more: https://nextjs.org/docs/app/api-reference/functions/generate-viewport
 ⚠ Unsupported metadata viewport is configured in metadata export in /profile. Please move it to viewport export instead.
   Generating static pages (13/19) [  ==]
 ⚠ Unsupported metadata viewport is configured in metadata export in /_not-found. Please move it to viewport export instead.
Read more: https://nextjs.org/docs/app/api-reference/functions/generate-viewport
 ⚠ Unsupported metadata viewport is configured in metadata export in /capacity. Please move it to viewport export instead.
Read more: https://nextjs.org/docs/app/api-reference/functions/generate-viewport
 ⚠ Unsupported metadata viewport is configured in metadata export in /reports. Please move it to viewport export instead.
   Generating static pages (13/19) [   =]
 ⚠ Unsupported metadata viewport is configured in metadata export in /reports. Please move it to viewport export instead.
Read more: https://nextjs.org/docs/app/api-reference/functions/generate-viewport
 ⚠ Unsupported metadata viewport is configured in metadata export in /capacity. Please move it to viewport export instead.
 ✓ Generating static pages (19/19)
 ✓ Collecting build traces
 ✓ Finalizing page optimization

Route (app)                              Size     First Load JS
┌ λ /                                    2.57 kB         206 kB
├ ○ /_not-found                          885 B          85.3 kB
├ λ /api/auth/[...nextauth]              0 B                0 B
├ λ /api/capacity                        0 B                0 B
├ λ /api/capacity/[id]                   0 B                0 B
├ λ /api/capacity/type/[id]              0 B                0 B
├ λ /api/capacity/users                  0 B                0 B
├ λ /api/language                        0 B                0 B
├ λ /api/list/[resource]                 0 B                0 B
├ λ /api/login                           0 B                0 B
├ λ /api/profile                         0 B                0 B
├ λ /api/profile_image                   0 B                0 B
├ λ /api/report                          0 B                0 B
├ λ /api/tag                             0 B                0 B
├ λ /api/users                           0 B                0 B
├ λ /capacity                            61.5 kB         265 kB
├ λ /capacity/[id]                       2.38 kB         205 kB
├ λ /oauth                               1.34 kB         101 kB
├ λ /profile                             155 B           215 kB
├ λ /profile/[id]                        155 B           215 kB
├ λ /profile/edit                        16 kB           227 kB
├ λ /reports                             1.71 kB         205 kB
├ λ /reports/[id]                        2.15 kB         205 kB
├ λ /reports/[id]/edit                   3.02 kB         206 kB
├ λ /tag/[category]/[id]                 2.05 kB         205 kB
└ ○ /terms                               287 B          96.5 kB
+ First Load JS shared by all            84.4 kB
  ├ chunks/69-d9cd0781fcc8755a.js        29 kB
  ├ chunks/fd9d1056-0179e5b51275d905.js  53.4 kB
  └ other shared chunks (total)          2.01 kB


ƒ Middleware                             26.4 kB

○  (Static)   prerendered as static content
λ  (Dynamic)  server-rendered on demand using Node.js

Done in 153.62s.
```
